### PR TITLE
Made PSMs more modular in preparation for reuse in simulation.

### PR DESCRIPTION
**Pull request by TomShkurti**
Added support for simulation modularity and control.

Made camera functional.

Minor changes to accomodate simulation.

Added simplified collisions.

### CODE REVIEW

**Comment by TomShkurti** [comment]
How did we end up in a situation where there's a "conflict" between the old version of the code and the fixes made to it? I'll see if I can resolve it on my own but @HutEight it'd be great if you were available to make a new PR with the code currently on the vision computer if this fork gets broken and has to be scrapped.

**Comment by TomShkurti** [comment]
Yeah this is not working. Can someone please make a fresh pull request using the geometry models file currently on the vision computer?

**Comment by biocubed** [comment]
@TomShkurti, When you get a chance, would it be possible for us to take some time and sort this PR out?

**Comment by TomShkurti** [comment]
I'm not able to resolve the conflicts remotely, I tried talking to Will but this may have to wait until I'm back physically.

**Pull request closed without merging**
